### ISSUE TITLE
Uploading a session and dsn pcb file currently isn't working properly

### ISSUE THREAD

**Issue by seveibar** [tscircuit/dsn-viewer#5]
It should display circuit json when you upload a dsn session and dsn pcb file. For some reason it's not working (and I've gtg!)

Here are two example files:

https://drive.google.com/drive/folders/16HmulzYGyWTsOq5d5p5teLj64ewRZXUH?usp=sharing

/bounty $20

**Comment by seveibar** [comment]
Make sure to turn on session upload mode

![Image](https://github.com/user-attachments/assets/6e25ab75-c98a-4d37-af8f-6a94f6a8c457)

**Comment by divanshu-go** [comment]
@seveibar currently when I do drag and drop , it only recognises dsnpcb.pcb

**Comment by divanshu-go** [comment]
![Image](https://github.com/user-attachments/assets/cc277954-4385-4e17-ba67-b1ed3e70d0ab)

**Comment by divanshu-go** [comment]
@seveibar maybe we should instead make a drag and drop zone , which would allow us to take both files one by one or both at same time

**Comment by seveibar** [comment]
@divanshu-go the ui is fine as-is. If it's not recognizing the files then that's part of the bug to fix
